#!/usr/bin/env bash
#
# F-004 — repository-owned REAL provider adapter (successor #4, finding F004-S3-R1-01).
#
# Successor-3 hash-bound only the deterministic local fixture; there was no repository
# real adapter, and the run-path guard checked only that the caller-supplied path was a
# file and executable. An independently byte-modified provider executable was therefore
# accepted by the real `run` path and produced `backup=success`. This file closes that:
# it is the ONE repository-owned adapter, its bytes are pinned in
# `scripts/ops/f004-adapter-identities.txt`, and the ops scripts refuse to take any
# provider action unless the adapter they were handed hashes to a pinned identity.
#
# SINGLE SOURCE OF TRUTH: `f004_argv` builds the exact argv for an operation. `--contract`
# prints that same argv for EVERY protocol operation together with its stdin/stdout/exit
# discipline, and the real execution path execs exactly what `f004_argv` produced. The
# published contract therefore cannot drift from what a real run would execute — it is
# generated by the same function, not restated in prose.
#
# AUTHOR STAGE: `--contract` and `--pinned-version` execute NOTHING. A real operation is
# refused with exit 4 unless F004_ADAPTER_REAL_EXEC=yes, which is controlled-live/founder
# territory. No credential is read, no network call is made, and no provider is contacted
# anywhere in this file's author-stage paths.
#
# F-027 BRIDGE: `record_backup_completed` writes the operational_events row the accepted
# deadman reads (`ops-health.js` latestOperationalEvent('backup_completed')). It targets the
# SOURCE D1 identity — the ledger is production state, not recovery-destination state — so
# source/destination isolation is unchanged: no destination credential or bucket is involved.
#
# TOOLCHAIN: pinned Wrangler (see F004_PINNED_WRANGLER, reconciled against
# workers/scan-api/package.json) plus an S3-compatible CLI for the operations Wrangler
# does not provide (Wrangler has no `r2 object list`). Streaming uses the supported forms
# only: `d1 export --remote --output <path>` (never `--output -`), `r2 object get/put
# --pipe --remote` (never `--file -`), and `aws s3 cp - | -` for stdin/stdout streaming.
#
set -euo pipefail
export LC_ALL=C

F004_PINNED_WRANGLER="4.120.0"

# Operation set = the union of the backup and restore protocol allowlists.
F004_ADAPTER_OPS="now backup_epoch verify_summary src_identity dest_identity r2_list d1_export r2_object store_put store_get dest_list record_backup_completed create_staging replay_d1 restore_r2 verify_d1 verify_r2 target_r2_list check_integrity check_fk check_schema check_tables check_rows check_r2"

die() { echo "f004 adapter FAILED: $*" >&2; exit 3; }

# Placeholder-defaulted identities. A real run supplies these; --contract renders the
# placeholders so the published argv is inspectable without any configuration.
SRC_D1="${F004_D1_NAME:-<src-d1>}"
SRC_BUCKET="${F004_R2_BUCKET:-<src-bucket>}"
SRC_ENDPOINT="${F004_S3_ENDPOINT:-<src-endpoint>}"
DEST_BUCKET="${F004_DEST_BUCKET:-<dest-bucket>}"
DEST_ENDPOINT="${F004_DEST_ENDPOINT:-<dest-endpoint>}"
TGT_BUCKET="${F004_TARGET_BUCKET:-<target-bucket>}"
EPOCH_FILE="${F004_BACKUP_EPOCH_FILE:-<backup-epoch-file>}"

# ── f004_argv <op> [args...] → fills the global array F004_ARGV with the exact command.
#    Every provider-touching operation resolves to a pinned Wrangler or S3-compatible
#    invocation; purely local operations resolve to a coreutil and touch no provider. ──
f004_argv() {
  local op="$1"; shift || true
  local a1="${1:-<arg1>}" a2="${2:-<arg2>}"
  case "$op" in
    now)            F004_ARGV=(date -u +%s) ;;
    backup_epoch)   F004_ARGV=(cat "$EPOCH_FILE") ;;
    verify_summary) F004_ARGV=(printf '%s\n' PASS) ;;
    src_identity)   F004_ARGV=(wrangler whoami --json) ;;
    dest_identity)  F004_ARGV=(aws sts get-caller-identity --endpoint-url "$DEST_ENDPOINT" --output text --query Account) ;;
    r2_list)        F004_ARGV=(aws s3api list-objects-v2 --bucket "$SRC_BUCKET" --endpoint-url "$SRC_ENDPOINT" --output text) ;;
    dest_list)      F004_ARGV=(aws s3api list-objects-v2 --bucket "$DEST_BUCKET" --endpoint-url "$DEST_ENDPOINT" --output text) ;;
    target_r2_list) F004_ARGV=(aws s3api list-objects-v2 --bucket "$TGT_BUCKET" --endpoint-url "$SRC_ENDPOINT" --output text) ;;
    d1_export)      F004_ARGV=(wrangler d1 export "$SRC_D1" --remote --output "${F004_ADAPTER_FIFO:-<adapter-fifo>}") ;;
    r2_object)      F004_ARGV=(wrangler r2 object get "$SRC_BUCKET/$a1" --pipe --remote) ;;
    store_put)      F004_ARGV=(aws s3 cp - "s3://$DEST_BUCKET/$a1" --endpoint-url "$DEST_ENDPOINT") ;;
    store_get)      F004_ARGV=(aws s3 cp "s3://$DEST_BUCKET/$a1" - --endpoint-url "$DEST_ENDPOINT") ;;
    record_backup_completed)
                    # ONE batched command: the idempotent write, then the exact confirming
                    # SELECT. meta.changes on statement 1 is the deterministic
                    # inserted-vs-existing signal; statement 2 proves the durable row.
                    F004_ARGV=(wrangler d1 execute "$SRC_D1" --remote --json --command "INSERT OR IGNORE INTO operational_events (id, workspace_id, event_type, correlation_id, status, attempts) VALUES ('$a2', NULL, 'backup_completed', '$a1', 'ok', 1); SELECT id, workspace_id, event_type, correlation_id, status, attempts FROM operational_events WHERE event_type = 'backup_completed' AND correlation_id = '$a1';") ;;
    create_staging) F004_ARGV=(wrangler d1 create "$a1") ;;
    replay_d1)      F004_ARGV=(wrangler d1 execute "$a1" --remote --file "${F004_ADAPTER_FIFO:-<adapter-fifo>}") ;;
    restore_r2)     F004_ARGV=(wrangler r2 object put "$TGT_BUCKET/$a2" --pipe --remote) ;;
    verify_r2)      F004_ARGV=(wrangler r2 object get "$TGT_BUCKET/$a2" --pipe --remote) ;;
    # verify_d1 measures the RESTORED STATE, not liveness: it re-exports the target and the
    # adapter digests the stream, so the answer is directly comparable to the manifest's D1
    # plaintext hash. `SELECT 1` could never establish that equality.
    verify_d1)      F004_ARGV=(wrangler d1 export "$a1" --remote --output "${F004_ADAPTER_FIFO:-<adapter-fifo>}") ;;
    check_integrity) F004_ARGV=(wrangler d1 execute "$a1" --remote --command 'PRAGMA integrity_check' --json) ;;
    check_fk)       F004_ARGV=(wrangler d1 execute "$a1" --remote --command 'PRAGMA foreign_key_check' --json) ;;
    check_schema)   F004_ARGV=(wrangler d1 execute "$a1" --remote --command 'SELECT type,name FROM sqlite_master ORDER BY name' --json) ;;
    check_tables)   F004_ARGV=(wrangler d1 execute "$a1" --remote --command 'SELECT count(*) FROM sqlite_master WHERE type=?' --json) ;;
    check_rows)     F004_ARGV=(wrangler d1 execute "$a1" --remote --command 'SELECT count(*) FROM sqlite_master' --json) ;;
    check_r2)       F004_ARGV=(aws s3api list-objects-v2 --bucket "$TGT_BUCKET" --endpoint-url "$SRC_ENDPOINT" --output text) ;;
    *) die "operation not in the adapter contract: $op" ;;
  esac
}

# ── Declared transforms, implemented (successor #5, finding F004-S4-R1-01) ────────────
# The contract declared fifo-stream / sha256-digest / account-id transforms that the byte did
# not implement: every operation except record_backup_completed fell through to a bare exec,
# so no FIFO was ever created and no provider output was ever digested. These are those
# transforms. They are part of the adapter's hash-bound bytes.

# A private, uniquely-named FIFO per invocation. mkfifo REFUSES an existing path, so a stale
# path can never be reused, and the enclosing directory is 0700 and removed on every exit or
# signal. A FIFO is not a regular file: no plaintext is ever staged on disk.
F004_FIFO_DIR=""
f004_fifo_cleanup() { [ -n "${F004_FIFO_DIR:-}" ] && rm -rf "$F004_FIFO_DIR"; F004_FIFO_DIR=""; }
trap 'f004_fifo_cleanup' EXIT
trap 'f004_fifo_cleanup; exit 130' HUP INT TERM

f004_make_fifo() {
  F004_FIFO_DIR="$(mktemp -d "${TMPDIR:-/tmp}/f004-adapter.XXXXXXXX")" || die "cannot create a private stream directory"
  chmod 700 "$F004_FIFO_DIR" || die "cannot confine the private stream directory"
  F004_ADAPTER_FIFO="$F004_FIFO_DIR/stream"
  mkfifo -m 600 "$F004_ADAPTER_FIFO" || die "cannot create a unique fifo"
  [ -p "$F004_ADAPTER_FIFO" ] || die "stream path is not a fifo"
}

f004_sha256_stream() { node -e 'const h=require("node:crypto").createHash("sha256");process.stdin.on("data",c=>h.update(c));process.stdin.on("end",()=>process.stdout.write(h.digest("hex")))'; }
f004_assert_digest() {
  case "${1:-}" in ""|*[!0-9a-f]*) return 1 ;; esac
  [ "${#1}" -eq 64 ] || return 1
  return 0
}

# fifo-stream, export direction: the provider writes export bytes into the FIFO; the adapter
# emits them on stdout. The reader runs in the background so a provider that never opens the
# FIFO cannot deadlock the adapter.
f004_stream_out() {
  cat "$F004_ADAPTER_FIFO" & local rd=$!
  if ! "${F004_ARGV[@]}"; then kill "$rd" 2>/dev/null || true; wait "$rd" 2>/dev/null || true; die "pinned export command failed"; fi
  wait "$rd" || die "export stream did not complete"
}

# fifo-stream, replay direction: the adapter supplies ITS OWN stdin through the FIFO to the
# provider's --file path. Stale file contents can never be replayed: the path is a fresh FIFO.
f004_stream_in() {
  # A background job in a non-interactive shell has stdin redirected to /dev/null, which
  # would silently supply ZERO bytes. Duplicate our real stdin onto fd 9 and read that.
  exec 9<&0
  cat <&9 > "$F004_ADAPTER_FIFO" & local wr=$!
  if ! "${F004_ARGV[@]}"; then kill "$wr" 2>/dev/null || true; wait "$wr" 2>/dev/null || true; die "pinned replay command failed"; fi
  wait "$wr" || die "replay stream did not complete"
}

# sha256-digest, via FIFO: digest what the provider exports, never emit the raw stream.
f004_digest_fifo() {
  # `cat` interposes deliberately: Node opens a FIFO given directly as stdin read-write, so it
  # holds its own write end and never observes EOF. Reading through cat gives Node an ordinary
  # pipe, which closes correctly when the provider finishes writing.
  ( cat < "$F004_ADAPTER_FIFO" | f004_sha256_stream > "$F004_FIFO_DIR/digest" ) & local rd=$!
  if ! "${F004_ARGV[@]}"; then kill "$rd" 2>/dev/null || true; wait "$rd" 2>/dev/null || true; die "pinned export command failed"; fi
  wait "$rd" || die "digest stream did not complete"
  local d; d="$(cat "$F004_FIFO_DIR/digest")"
  f004_assert_digest "$d" || die "measured state did not digest to one sha-256"
  printf '%s\n' "$d"
}

# sha256-digest, via pipe: digest the provider's stdout, never emit the raw object bytes.
f004_digest_pipe() {
  local d; d="$( "${F004_ARGV[@]}" | f004_sha256_stream )" || die "pinned object read failed"
  f004_assert_digest "$d" || die "measured object did not digest to one sha-256"
  printf '%s\n' "$d"
}

# account-id transform (successor #5, finding F004-S4-R1-02): MEASURE the account the source
# credential context actually selects. A caller-supplied label is a claim, not evidence, so the
# caller compares this measurement to its claim and stops on mismatch. Ambiguity fails closed:
# a credential context holding more than one account does not determine the operating account.
F004_ACCOUNT_JS='
let raw = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (c) => { raw += c; });
process.stdin.on("end", () => {
  const fail = (m) => { process.stderr.write("f004 adapter: " + m + "\n"); process.exit(7); };
  let doc;
  try { doc = JSON.parse(raw); } catch { fail("account identity result is not valid JSON"); }
  const accounts = doc && Array.isArray(doc.accounts) ? doc.accounts : null;
  if (!accounts) fail("account identity result carries no accounts array");
  if (accounts.length === 0) fail("credential context selects no account");
  if (accounts.length > 1) fail("credential context is ambiguous: " + accounts.length + " accounts; scope the token to one");
  const id = accounts[0] && (accounts[0].id ?? accounts[0].account_id);
  if (typeof id !== "string" || !/^[A-Za-z0-9._-]{1,128}$/.test(id)) fail("measured account id is missing or malformed");
  process.stdout.write(id + "\n");
});
'
f004_account_id() { node -e "$F004_ACCOUNT_JS"; }

# ── record_backup_completed: argument validation + the JSON parse/confirm transform ──
# Wrangler returns raw JSON; the protocol requires an exact acknowledgement. This is the
# transformation, and it is part of the adapter's hash-bound bytes. It is exposed as
# `--confirm-json` so the exact parser can be proven against representative real Wrangler
# shapes WITHOUT a provider. Provider self-report is never accepted: the durable row itself
# must match on every field before any acknowledgement is emitted.
f004_assert_event_args() {
  case "${1:-}" in ""|*[!A-Za-z0-9_:.-]*) die "correlation id is malformed for record_backup_completed" ;; esac
  case "${2:-}" in opev_[0-9a-f]*) : ;; *) die "event id is malformed for record_backup_completed" ;; esac
  [ "${#2}" -eq 37 ] || die "event id is not opev_ + 32 hex"
}

F004_CONFIRM_JS='
const wantId = process.argv[1] || "";
const wantCorr = process.argv[2] || "";
let raw = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (c) => { raw += c; });
process.stdin.on("end", () => {
  const fail = (m) => { process.stderr.write("f004 adapter: " + m + "\n"); process.exit(6); };
  if (!/^opev_[0-9a-f]{32}$/.test(wantId)) fail("requested event id is malformed");
  if (!/^[\w:.\-]{1,200}$/.test(wantCorr)) fail("requested correlation id is malformed");
  let doc;
  try { doc = JSON.parse(raw); } catch { fail("wrangler result is not valid JSON"); }
  if (!Array.isArray(doc) || doc.length < 2) fail("expected one result per batched statement");
  const ins = doc[0], sel = doc[1];
  if (!ins || ins.success !== true) fail("the write statement did not report success");
  if (!sel || sel.success !== true) fail("the confirming select did not report success");
  const changes = ins.meta && ins.meta.changes;
  if (changes !== 0 && changes !== 1) fail("no deterministic inserted-vs-existing signal");
  const rows = sel.results;
  if (!Array.isArray(rows)) fail("confirming select returned no result set");
  if (rows.length !== 1) fail("confirming select did not return exactly one row");
  const r = rows[0];
  if (r.id !== wantId) fail("durable row id is not the requested event id");
  if (r.workspace_id !== null) fail("durable row workspace_id is not NULL");
  if (r.event_type !== "backup_completed") fail("durable row event_type is not backup_completed");
  if (r.correlation_id !== wantCorr) fail("durable row correlation_id is not the requested token");
  if (r.status !== "ok") fail("durable row status is not ok");
  if (Number(r.attempts) !== 1) fail("durable row attempts is not 1");
  process.stdout.write((changes === 1 ? "recorded " : "duplicate ") + wantId + "\n");
});
'
f004_confirm_json() { node -e "$F004_CONFIRM_JS" "${1:-}" "${2:-}"; }

# ── Per-operation stdin/stdout/exit discipline, kept beside the argv it describes.
#    NOTE the FIFO indirection: `d1_export` and `replay_d1` present a BYTE STREAM to the
#    protocol, while the pinned CLI underneath reads/writes a PATH. That is exactly why the
#    supported forms are `--output <path>` / `--file <path>` and never `--output -` /
#    `--file -`; the adapter owns the FIFO on both sides.
#    NOTE also the verification transforms: `verify_d1` and `verify_r2` present TEXT (a
#    sha256 of what the target actually holds) to the protocol, while the CLI underneath
#    streams object bytes or query rows. The adapter hashes; the protocol compares.
#    `record_backup_completed` is the same shape: the CLI underneath runs one INSERT OR
#    IGNORE into the SOURCE database's F-027 operational_events ledger, and the adapter
#    presents TEXT — `recorded <id>` or `duplicate <id>` — so the caller can confirm the
#    exact row it derived is durably present. A duplicate is durable success, because
#    UNIQUE(event_type, correlation_id) makes one logical backup one row. ──
f004_io() {   # → "<kind> <stdin> <stdout> <exit> <transform>"
  case "$1" in
    d1_export)                        printf 'wrangler none bytes zero-on-success fifo-stream' ;;
    r2_object)                        printf 'wrangler none bytes zero-on-success none' ;;
    restore_r2)                       printf 'wrangler bytes none zero-on-success none' ;;
    replay_d1)                        printf 'wrangler bytes none zero-on-success fifo-stream' ;;
    verify_r2)                        printf 'wrangler none text zero-on-success sha256-digest' ;;
    record_backup_completed)          printf 'wrangler none text zero-on-success confirm-json' ;;
    verify_d1)                        printf 'wrangler none text zero-on-success sha256-digest' ;;
    create_staging|check_integrity|check_fk|check_schema|check_tables|check_rows)
                                      printf 'wrangler none text zero-on-success none' ;;
    store_put)                        printf 'aws bytes none zero-on-success none' ;;
    store_get)                        printf 'aws none bytes zero-on-success none' ;;
    r2_list|dest_list|target_r2_list|check_r2|dest_identity)
                                      printf 'aws none text zero-on-success none' ;;
    src_identity)                     printf 'wrangler none text zero-on-success account-id' ;;
    now|backup_epoch|verify_summary)  printf 'local none text zero-on-success none' ;;
    *) die "no i/o discipline declared for operation: $1" ;;
  esac
}

if [ "${1:-}" = "--account-id" ]; then
  # Parse/measure an account identity result. No provider is contacted; stdin is the JSON.
  shift; f004_account_id; exit $?
fi
if [ "${1:-}" = "--digest" ]; then
  # Digest stdin exactly as the sha256-digest transform does. No provider is contacted.
  shift; d="$(f004_sha256_stream)"; f004_assert_digest "$d" || die "input did not digest to one sha-256"; printf '%s\n' "$d"; exit 0
fi
if [ "${1:-}" = "--confirm-json" ]; then
  # Parse/confirm a Wrangler d1 result. No provider is contacted; stdin is the JSON.
  shift; f004_confirm_json "${1:-}" "${2:-}"; exit $?
fi
if [ "${1:-}" = "--pinned-version" ]; then printf '%s\n' "$F004_PINNED_WRANGLER"; exit 0; fi
if [ "${1:-}" = "--ops" ]; then printf '%s\n' $F004_ADAPTER_OPS; exit 0; fi
if [ "${1:-}" = "--contract" ]; then
  # Executes nothing. Emits: op <TAB> kind <TAB> stdin <TAB> stdout <TAB> exit <TAB> argv
  for op in $F004_ADAPTER_OPS; do
    f004_argv "$op"
    set -- $(f004_io "$op")
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$op" "$1" "$2" "$3" "$4" "$5" "${F004_ARGV[*]}"
  done
  exit 0
fi

# ── Real provider execution. Hard-gated: the author stage never enables it. ──
op="${1:-}"; shift || true
case " $F004_ADAPTER_OPS " in *" $op "*) : ;; *) die "operation not in the adapter contract: $op" ;; esac
if [ "${F004_ADAPTER_REAL_EXEC:-no}" != "yes" ]; then
  echo "f004 adapter: real provider execution is disabled (op: $op). Author-stage runs never contact a provider; set F004_ADAPTER_REAL_EXEC=yes only under controlled-live authority." >&2
  exit 4
fi
if [ "$op" = "record_backup_completed" ]; then
  f004_assert_event_args "${1:-}" "${2:-}"
  f004_argv "$op" "$@"
  # NOT a bare exec: Wrangler's raw JSON is never the protocol answer. Run the pinned
  # command, then parse and confirm the durable row before emitting an acknowledgement.
  out="$("${F004_ARGV[@]}")" || die "pinned d1 execute failed for record_backup_completed"
  printf '%s' "$out" | f004_confirm_json "${2:-}" "${1:-}"
  exit $?
fi
case "$op" in
  d1_export)
    f004_make_fifo; f004_argv "$op" "$@"; f004_stream_out; exit 0 ;;
  replay_d1)
    f004_make_fifo; f004_argv "$op" "$@"; f004_stream_in; exit 0 ;;
  verify_d1)
    f004_make_fifo; f004_argv "$op" "$@"; f004_digest_fifo; exit 0 ;;
  verify_r2)
    f004_argv "$op" "$@"; f004_digest_pipe; exit 0 ;;
  src_identity)
    f004_argv "$op" "$@"
    out="$("${F004_ARGV[@]}")" || die "pinned account identity command failed"
    printf '%s' "$out" | f004_account_id; exit $? ;;
esac
f004_argv "$op" "$@"
exec "${F004_ARGV[@]}"
