-- Migration 048: Microsoft Entra OAuth columns
--
-- Adds Microsoft identity fields to users table and a temporary oauth_states
-- table for CSRF state verification during the OAuth authorization code flow.
--
-- Changes to users table:
--   auth_provider TEXT  — 'local' | 'microsoft' | NULL (NULL = legacy/local)
--   microsoft_oid TEXT  — Microsoft Object ID (stable per-tenant user identifier)
--   tenant_id TEXT      — Azure AD Tenant ID the user authenticated against
--
-- oauth_states table:
--   Short-lived CSRF tokens generated by GET /api/auth/microsoft/login.
--   Deleted on use in GET /api/auth/microsoft/callback.
--   Rows with expires_at < now() are safe to purge.
--
-- Apply:
--   wrangler d1 execute cybermeters-db --remote \
--     --file=database/migrations/048-microsoft-auth.sql
--
-- Validation:
--   PRAGMA table_info(users);
--   -- Expect: auth_provider, microsoft_oid, tenant_id columns present
--   SELECT name FROM sqlite_master WHERE type='table' AND name='oauth_states';
--
-- Rollback:
--   D1/SQLite does not support DROP COLUMN.
--   Columns are nullable — safe to leave in place.
--   oauth_states can be dropped: DROP TABLE IF EXISTS oauth_states;

-- ── Extend users table ────────────────────────────────────────────────────────

-- auth_provider: identifies how the account was created / how the user logs in.
-- NULL or 'local' = email/password. 'microsoft' = Microsoft Entra OAuth.
ALTER TABLE users ADD COLUMN auth_provider TEXT;

-- microsoft_oid: Azure AD Object ID. Stable per user per tenant.
-- Used as the primary lookup key for Microsoft-authenticated users.
ALTER TABLE users ADD COLUMN microsoft_oid TEXT;

-- tenant_id: Azure AD Tenant ID (tid claim from id_token).
-- Stored for multi-tenant visibility and future tenant-scoped enforcement.
ALTER TABLE users ADD COLUMN tenant_id TEXT;

-- Unique partial index: enforces one user row per microsoft_oid,
-- while allowing NULL for non-Microsoft accounts.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_microsoft_oid
  ON users (microsoft_oid)
  WHERE microsoft_oid IS NOT NULL;

-- ── oauth_states table ────────────────────────────────────────────────────────

-- Temporary CSRF state tokens for the OAuth authorization code flow.
-- Each state is single-use: deleted immediately after callback validation.
-- expires_at enforces a 10-minute window for the authorization flow.

CREATE TABLE IF NOT EXISTS oauth_states (
  state        TEXT PRIMARY KEY,
  provider     TEXT NOT NULL DEFAULT 'microsoft',
  redirect_uri TEXT,
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at   TEXT NOT NULL
);

-- Index for efficient expiry-based cleanup
CREATE INDEX IF NOT EXISTS idx_oauth_states_expires_at
  ON oauth_states (expires_at);
