-- GENERATED by scripts/generate-migration-105.js from applied migrations 103/104.
-- Do not edit this file directly; regenerate and run the migration-105 proofs.
-- Founder gate: prepared only. Never apply to production as part of this PR.

-- Governed production carrier after a separate founder gate:
-- npx wrangler d1 execute cybermeters-db --remote \
--   --file=../../database/migrations/105-ct-platform-deadline-provenance.sql

PRAGMA defer_foreign_keys = on;

CREATE TABLE ct_platform_deadline_migration_105_guard (
    table_name    TEXT PRIMARY KEY,
    source_count INTEGER NOT NULL,
    copied_count INTEGER NOT NULL,
    CHECK (source_count = copied_count)
);

CREATE TABLE ct_provider_overlap_telemetry__105 (
    id                                      TEXT PRIMARY KEY,
    scan_id                                 TEXT NOT NULL,
    module                                  TEXT NOT NULL CHECK (module = 'subdomains'),
    source_set_version                      TEXT NOT NULL,
    observed_at                             TEXT NOT NULL,
    normalization_candidate_limit           INTEGER NOT NULL CHECK (normalization_candidate_limit > 0),
    retained_hostname_limit                 INTEGER NOT NULL CHECK (
                                              retained_hostname_limit > 0 AND
                                              retained_hostname_limit <= normalization_candidate_limit
                                            ),

    crt_sh_attempt_state                    TEXT NOT NULL CHECK (crt_sh_attempt_state IN (
                                              'terminal_success', 'terminal_failure',
                                              'terminal_platform_deadline_abort',
                                              'not_started', 'in_flight_at_consumer_release'
                                            )),
    crt_sh_raw_record_count                 INTEGER CHECK (crt_sh_raw_record_count >= 0),
    crt_sh_expanded_candidate_count         INTEGER CHECK (crt_sh_expanded_candidate_count >= 0),
    crt_sh_normalization_input_count        INTEGER CHECK (crt_sh_normalization_input_count >= 0),
    crt_sh_normalization_dropped_candidate_count INTEGER CHECK (crt_sh_normalization_dropped_candidate_count >= 0),
    crt_sh_normalization_truncated          INTEGER CHECK (crt_sh_normalization_truncated IN (0, 1)),
    crt_sh_normalized_candidate_count       INTEGER CHECK (crt_sh_normalized_candidate_count >= 0),
    crt_sh_unique_hostname_count            INTEGER CHECK (crt_sh_unique_hostname_count >= 0),
    crt_sh_retained_hostname_count          INTEGER CHECK (crt_sh_retained_hostname_count >= 0),
    crt_sh_dropped_hostname_count           INTEGER CHECK (crt_sh_dropped_hostname_count >= 0),
    crt_sh_truncated                        INTEGER CHECK (crt_sh_truncated IN (0, 1)),

    certspotter_attempt_state               TEXT NOT NULL CHECK (certspotter_attempt_state IN (
                                              'terminal_success', 'terminal_failure',
                                              'terminal_platform_deadline_abort',
                                              'not_started', 'in_flight_at_consumer_release'
                                            )),
    certspotter_raw_record_count            INTEGER CHECK (certspotter_raw_record_count >= 0),
    certspotter_expanded_candidate_count    INTEGER CHECK (certspotter_expanded_candidate_count >= 0),
    certspotter_normalization_input_count   INTEGER CHECK (certspotter_normalization_input_count >= 0),
    certspotter_normalization_dropped_candidate_count INTEGER CHECK (certspotter_normalization_dropped_candidate_count >= 0),
    certspotter_normalization_truncated     INTEGER CHECK (certspotter_normalization_truncated IN (0, 1)),
    certspotter_normalized_candidate_count  INTEGER CHECK (certspotter_normalized_candidate_count >= 0),
    certspotter_unique_hostname_count       INTEGER CHECK (certspotter_unique_hostname_count >= 0),
    certspotter_retained_hostname_count     INTEGER CHECK (certspotter_retained_hostname_count >= 0),
    certspotter_dropped_hostname_count      INTEGER CHECK (certspotter_dropped_hostname_count >= 0),
    certspotter_truncated                   INTEGER CHECK (certspotter_truncated IN (0, 1)),

    comparison_status                       TEXT NOT NULL CHECK (comparison_status IN (
                                              'compared', 'compared_truncated',
                                              'censored_provider_failure',
                                              'censored_platform_deadline_abort',
                                              'censored_in_flight', 'not_started'
                                            )),
    intersection_count                      INTEGER CHECK (intersection_count >= 0),
    crt_sh_only_count                       INTEGER CHECK (crt_sh_only_count >= 0),
    certspotter_only_count                  INTEGER CHECK (certspotter_only_count >= 0),
    union_count                             INTEGER CHECK (union_count >= 0),
    created_at                              TEXT NOT NULL DEFAULT (datetime('now')),

    FOREIGN KEY (scan_id) REFERENCES scans(id),
    UNIQUE (scan_id, module, source_set_version),

    CHECK (
      (
        crt_sh_attempt_state = 'terminal_success' AND
        crt_sh_raw_record_count IS NOT NULL AND
        crt_sh_expanded_candidate_count IS NOT NULL AND
        crt_sh_normalization_input_count IS NOT NULL AND
        crt_sh_normalization_dropped_candidate_count IS NOT NULL AND
        crt_sh_normalization_truncated IS NOT NULL AND
        crt_sh_normalized_candidate_count IS NOT NULL AND
        crt_sh_unique_hostname_count IS NOT NULL AND
        crt_sh_retained_hostname_count IS NOT NULL AND
        crt_sh_dropped_hostname_count IS NOT NULL AND
        crt_sh_truncated IS NOT NULL AND
        crt_sh_normalization_input_count + crt_sh_normalization_dropped_candidate_count = crt_sh_expanded_candidate_count AND
        crt_sh_normalized_candidate_count <= crt_sh_normalization_input_count AND
        crt_sh_unique_hostname_count <= crt_sh_normalized_candidate_count AND
        crt_sh_unique_hostname_count = crt_sh_retained_hostname_count + crt_sh_dropped_hostname_count AND
        crt_sh_retained_hostname_count <= retained_hostname_limit AND
        crt_sh_normalization_truncated = (crt_sh_normalization_dropped_candidate_count > 0) AND
        crt_sh_truncated = (crt_sh_dropped_hostname_count > 0)
      ) OR (
        crt_sh_attempt_state != 'terminal_success' AND
        crt_sh_raw_record_count IS NULL AND crt_sh_expanded_candidate_count IS NULL AND
        crt_sh_normalization_input_count IS NULL AND crt_sh_normalization_dropped_candidate_count IS NULL AND
        crt_sh_normalization_truncated IS NULL AND crt_sh_normalized_candidate_count IS NULL AND
        crt_sh_unique_hostname_count IS NULL AND crt_sh_retained_hostname_count IS NULL AND
        crt_sh_dropped_hostname_count IS NULL AND crt_sh_truncated IS NULL
      )
    ),
    CHECK (
      (
        certspotter_attempt_state = 'terminal_success' AND
        certspotter_raw_record_count IS NOT NULL AND
        certspotter_expanded_candidate_count IS NOT NULL AND
        certspotter_normalization_input_count IS NOT NULL AND
        certspotter_normalization_dropped_candidate_count IS NOT NULL AND
        certspotter_normalization_truncated IS NOT NULL AND
        certspotter_normalized_candidate_count IS NOT NULL AND
        certspotter_unique_hostname_count IS NOT NULL AND
        certspotter_retained_hostname_count IS NOT NULL AND
        certspotter_dropped_hostname_count IS NOT NULL AND
        certspotter_truncated IS NOT NULL AND
        certspotter_normalization_input_count + certspotter_normalization_dropped_candidate_count = certspotter_expanded_candidate_count AND
        certspotter_normalized_candidate_count <= certspotter_normalization_input_count AND
        certspotter_unique_hostname_count <= certspotter_normalized_candidate_count AND
        certspotter_unique_hostname_count = certspotter_retained_hostname_count + certspotter_dropped_hostname_count AND
        certspotter_retained_hostname_count <= retained_hostname_limit AND
        certspotter_normalization_truncated = (certspotter_normalization_dropped_candidate_count > 0) AND
        certspotter_truncated = (certspotter_dropped_hostname_count > 0)
      ) OR (
        certspotter_attempt_state != 'terminal_success' AND
        certspotter_raw_record_count IS NULL AND certspotter_expanded_candidate_count IS NULL AND
        certspotter_normalization_input_count IS NULL AND certspotter_normalization_dropped_candidate_count IS NULL AND
        certspotter_normalization_truncated IS NULL AND certspotter_normalized_candidate_count IS NULL AND
        certspotter_unique_hostname_count IS NULL AND certspotter_retained_hostname_count IS NULL AND
        certspotter_dropped_hostname_count IS NULL AND certspotter_truncated IS NULL
      )
    ),
    CHECK (
      (
        comparison_status IN ('compared', 'compared_truncated') AND
        crt_sh_attempt_state = 'terminal_success' AND
        certspotter_attempt_state = 'terminal_success' AND
        intersection_count IS NOT NULL AND crt_sh_only_count IS NOT NULL AND
        certspotter_only_count IS NOT NULL AND union_count IS NOT NULL AND
        union_count = intersection_count + crt_sh_only_count + certspotter_only_count AND
        (comparison_status = 'compared_truncated') = (
          crt_sh_truncated = 1 OR certspotter_truncated = 1 OR
          crt_sh_normalization_truncated = 1 OR certspotter_normalization_truncated = 1
        )
      ) OR (
        comparison_status NOT IN ('compared', 'compared_truncated') AND
        intersection_count IS NULL AND crt_sh_only_count IS NULL AND
        certspotter_only_count IS NULL AND union_count IS NULL
      )
    ),
    CHECK (
      comparison_status != 'censored_provider_failure' OR
      (crt_sh_attempt_state = 'terminal_failure' OR certspotter_attempt_state = 'terminal_failure')
    ),
    CHECK (
      comparison_status != 'censored_in_flight' OR
      (crt_sh_attempt_state = 'in_flight_at_consumer_release' OR
       certspotter_attempt_state = 'in_flight_at_consumer_release')
    ),
    CHECK (
      comparison_status != 'not_started' OR
      (crt_sh_attempt_state = 'not_started' OR certspotter_attempt_state = 'not_started')
    ),
    CHECK (
      (
        comparison_status = 'censored_platform_deadline_abort' AND
        (crt_sh_attempt_state = 'terminal_platform_deadline_abort' OR
         certspotter_attempt_state = 'terminal_platform_deadline_abort') AND
        crt_sh_attempt_state != 'in_flight_at_consumer_release' AND
        certspotter_attempt_state != 'in_flight_at_consumer_release'
      ) OR (
        comparison_status != 'censored_platform_deadline_abort' AND
        crt_sh_attempt_state != 'terminal_platform_deadline_abort' AND
        certspotter_attempt_state != 'terminal_platform_deadline_abort'
      )
    )
);
-- FAILURE_INJECTION_AFTER_NEW_TABLE_CREATION

INSERT INTO ct_provider_overlap_telemetry__105 (
    id, scan_id, module, source_set_version,
    observed_at, normalization_candidate_limit, retained_hostname_limit, crt_sh_attempt_state,
    crt_sh_raw_record_count, crt_sh_expanded_candidate_count, crt_sh_normalization_input_count, crt_sh_normalization_dropped_candidate_count,
    crt_sh_normalization_truncated, crt_sh_normalized_candidate_count, crt_sh_unique_hostname_count, crt_sh_retained_hostname_count,
    crt_sh_dropped_hostname_count, crt_sh_truncated, certspotter_attempt_state, certspotter_raw_record_count,
    certspotter_expanded_candidate_count, certspotter_normalization_input_count, certspotter_normalization_dropped_candidate_count, certspotter_normalization_truncated,
    certspotter_normalized_candidate_count, certspotter_unique_hostname_count, certspotter_retained_hostname_count, certspotter_dropped_hostname_count,
    certspotter_truncated, comparison_status, intersection_count, crt_sh_only_count,
    certspotter_only_count, union_count, created_at
)
SELECT
    id, scan_id, module, source_set_version,
    observed_at, normalization_candidate_limit, retained_hostname_limit, crt_sh_attempt_state,
    crt_sh_raw_record_count, crt_sh_expanded_candidate_count, crt_sh_normalization_input_count, crt_sh_normalization_dropped_candidate_count,
    crt_sh_normalization_truncated, crt_sh_normalized_candidate_count, crt_sh_unique_hostname_count, crt_sh_retained_hostname_count,
    crt_sh_dropped_hostname_count, crt_sh_truncated, certspotter_attempt_state, certspotter_raw_record_count,
    certspotter_expanded_candidate_count, certspotter_normalization_input_count, certspotter_normalization_dropped_candidate_count, certspotter_normalization_truncated,
    certspotter_normalized_candidate_count, certspotter_unique_hostname_count, certspotter_retained_hostname_count, certspotter_dropped_hostname_count,
    certspotter_truncated, comparison_status, intersection_count, crt_sh_only_count,
    certspotter_only_count, union_count, created_at
FROM ct_provider_overlap_telemetry;
-- FAILURE_INJECTION_AFTER_HISTORICAL_ROW_COPY

INSERT INTO ct_platform_deadline_migration_105_guard
    (table_name, source_count, copied_count)
SELECT 'ct_provider_overlap_telemetry',
       (SELECT COUNT(*) FROM ct_provider_overlap_telemetry),
       (SELECT COUNT(*) FROM ct_provider_overlap_telemetry__105);

DROP TABLE ct_provider_overlap_telemetry;
ALTER TABLE ct_provider_overlap_telemetry__105
  RENAME TO ct_provider_overlap_telemetry;
-- FAILURE_INJECTION_AT_OLD_TABLE_DROP_RENAME_BOUNDARY

CREATE INDEX idx_ct_provider_overlap_telemetry_scan
  ON ct_provider_overlap_telemetry (scan_id, observed_at);
-- FAILURE_INJECTION_AFTER_FIRST_NAMED_INDEX_RECREATION

CREATE INDEX idx_ct_provider_overlap_telemetry_status_time
  ON ct_provider_overlap_telemetry (comparison_status, observed_at);
-- FAILURE_INJECTION_AFTER_FIRST_TABLE_BEFORE_SECOND

CREATE TABLE ct_provider_telemetry__105 (
    id                    TEXT PRIMARY KEY,
    scan_id               TEXT NOT NULL,
    module                TEXT NOT NULL CHECK (module IN ('ssl', 'subdomains')),
    provider              TEXT NOT NULL CHECK (provider IN ('crt_sh', 'certspotter')),
    outcome               TEXT NOT NULL CHECK (
                            outcome IN (
                              'ok', 'timeout', 'http_error', 'parse_error',
                              'rate_limited', 'network_error',
                              'platform_deadline_abort'
                            )
                          ),
    http_status           INTEGER CHECK (
                            http_status IS NULL OR
                            (http_status BETWEEN 100 AND 599)
                          ),
    latency_ms            INTEGER NOT NULL CHECK (latency_ms >= 0),
    result_count          INTEGER CHECK (result_count IS NULL OR result_count >= 0),
    started_at            TEXT NOT NULL,
    completed_at          TEXT NOT NULL,
    completeness_impact   INTEGER NOT NULL DEFAULT 0 CHECK (
                            completeness_impact IN (0, 1)
                          ),
    affected_signal       TEXT CHECK (
                            (completeness_impact = 0 AND affected_signal IS NULL) OR
                            (completeness_impact = 1 AND affected_signal IN (
                              'certificate_transparency',
                              'subdomain_discovery'
                            ))
                          ),
    cache_state           TEXT NOT NULL DEFAULT 'miss' CHECK (
                            cache_state IN ('miss', 'fresh_hit', 'stale_available')
                          ),
    cache_age_s           INTEGER CHECK (cache_age_s IS NULL OR cache_age_s >= 0),
    created_at            TEXT NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (scan_id) REFERENCES scans(id),
    CHECK (
      outcome != 'platform_deadline_abort' OR
      (http_status IS NULL AND result_count IS NULL)
    )
);

INSERT INTO ct_provider_telemetry__105 (
    id, scan_id, module, provider,
    outcome, http_status, latency_ms, result_count,
    started_at, completed_at, completeness_impact, affected_signal,
    cache_state, cache_age_s, created_at
)
SELECT
    id, scan_id, module, provider,
    outcome, http_status, latency_ms, result_count,
    started_at, completed_at, completeness_impact, affected_signal,
    cache_state, cache_age_s, created_at
FROM ct_provider_telemetry;

INSERT INTO ct_platform_deadline_migration_105_guard
    (table_name, source_count, copied_count)
SELECT 'ct_provider_telemetry',
       (SELECT COUNT(*) FROM ct_provider_telemetry),
       (SELECT COUNT(*) FROM ct_provider_telemetry__105);

DROP TABLE ct_provider_telemetry;
ALTER TABLE ct_provider_telemetry__105 RENAME TO ct_provider_telemetry;

CREATE INDEX idx_ct_provider_telemetry_scan
  ON ct_provider_telemetry (scan_id, module, provider);

CREATE INDEX idx_ct_provider_telemetry_provider_time
  ON ct_provider_telemetry (provider, started_at);

-- Two providers × two module consumers × the existing two-attempt hard cap.
-- Runtime collection is bounded too; this trigger is the durable fail-closed guard.
CREATE TRIGGER trg_ct_provider_telemetry_scan_row_bound
BEFORE INSERT ON ct_provider_telemetry
WHEN (
  SELECT COUNT(*)
  FROM ct_provider_telemetry
  WHERE scan_id = NEW.scan_id
) >= 8
BEGIN
  SELECT RAISE(ABORT, 'ct_provider_telemetry row bound exceeded');
END;
-- FAILURE_INJECTION_DURING_TRIGGER_RECREATION

INSERT INTO ct_platform_deadline_migration_105_guard
    (table_name, source_count, copied_count)
SELECT 'ct_provider_telemetry_scan_fk', 0, COUNT(*)
FROM ct_provider_telemetry AS telemetry
LEFT JOIN scans ON scans.id = telemetry.scan_id
WHERE scans.id IS NULL;

INSERT INTO ct_platform_deadline_migration_105_guard
    (table_name, source_count, copied_count)
SELECT 'ct_provider_overlap_telemetry_scan_fk', 0, COUNT(*)
FROM ct_provider_overlap_telemetry AS telemetry
LEFT JOIN scans ON scans.id = telemetry.scan_id
WHERE scans.id IS NULL;

DROP TABLE ct_platform_deadline_migration_105_guard;

PRAGMA foreign_key_check;
